# Generated by Django 5.1.5 on 2025-01-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='photo',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
